/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ec.edu.viajecito.view;

import ec.edu.viajecito.controller.BoletosController;
import ec.edu.viajecito.controller.CiudadesController;
import ec.edu.viajecito.controller.VuelosController;
import ec.edu.viajecito.model.Ciudad;
import ec.edu.viajecito.model.CompraBoletoRequest;
import ec.edu.viajecito.model.Usuario;
import ec.edu.viajecito.model.Vuelo;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Drouet
 */
public class ComprarFrm extends javax.swing.JFrame {

    private Usuario usuario;
    private List<Ciudad> ciudades;
    private List<Vuelo> vuelos;
    
    /**
     * Creates new form LoginFrm
     */
    public ComprarFrm(Usuario usuario1) {
        initComponents();
        SpinnerDateModel model = new SpinnerDateModel();
        spinDate.setModel(model);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(spinDate, "yyyy-MM-dd");
        spinDate.setEditor(editor);
        SpinnerNumberModel model1 = new SpinnerNumberModel(0, 0, Integer.MAX_VALUE, 1);
        spnNumBoletos.setModel(model1);
        cargarCiudadesEnCombo();
        
        this.usuario = usuario1;
        vuelos = new ArrayList<>();

    }
    
    private void cargarCiudadesEnCombo() {
        ciudades = new CiudadesController().obtenerTodasCiudades();
        cmbOrigen.removeAllItems();
        cmbDestino.removeAllItems();

        for (Ciudad c : ciudades) {
            cmbOrigen.addItem(c.getCodigoCiudad() + " - " + c.getNombreCiudad());
            cmbDestino.addItem(c.getCodigoCiudad() + " - " + c.getNombreCiudad());
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dialogConfirm = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnComprar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblViajesMsg = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        cmbOrigen = new javax.swing.JComboBox<>();
        cmbDestino = new javax.swing.JComboBox<>();
        spinDate = new javax.swing.JSpinner();
        cmbVuelos = new javax.swing.JComboBox<>();
        spnNumBoletos = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        btnSalir1 = new javax.swing.JButton();
        btnBuscar = new javax.swing.JButton();

        dialogConfirm.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N

        javax.swing.GroupLayout dialogConfirmLayout = new javax.swing.GroupLayout(dialogConfirm.getContentPane());
        dialogConfirm.getContentPane().setLayout(dialogConfirmLayout);
        dialogConfirmLayout.setHorizontalGroup(
            dialogConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        dialogConfirmLayout.setVerticalGroup(
            dialogConfirmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(253, 195, 70));
        jPanel1.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setBackground(new java.awt.Color(60, 59, 46));
        jLabel2.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(60, 59, 46));
        jLabel2.setText("Vuelos Disponibles:");

        jLabel3.setBackground(new java.awt.Color(27, 27, 30));
        jLabel3.setFont(new java.awt.Font("Maiandra GD", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(60, 59, 46));
        jLabel3.setText("Comprar Boletos");

        jLabel4.setBackground(new java.awt.Color(60, 59, 46));
        jLabel4.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(27, 55, 58));
        jLabel4.setText("Fecha de Viaje:");

        btnComprar.setBackground(new java.awt.Color(35, 103, 138));
        btnComprar.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
        btnComprar.setText("Comprar");
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(27, 27, 30));
        jLabel5.setFont(new java.awt.Font("Maiandra GD", 1, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(60, 59, 46));
        jLabel5.setText("VIAJECITO S.A.");

        lblViajesMsg.setBackground(new java.awt.Color(60, 59, 46));
        lblViajesMsg.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        lblViajesMsg.setForeground(new java.awt.Color(60, 59, 46));

        jLabel8.setBackground(new java.awt.Color(60, 59, 46));
        jLabel8.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(27, 55, 58));
        jLabel8.setText("Ciudad de Origen:");

        jLabel9.setBackground(new java.awt.Color(60, 59, 46));
        jLabel9.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(27, 55, 58));
        jLabel9.setText("Ciudad de Destino:");

        cmbOrigen.setBackground(new java.awt.Color(255, 255, 255));
        cmbOrigen.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cmbOrigen.setForeground(new java.awt.Color(60, 59, 46));

        cmbDestino.setBackground(new java.awt.Color(255, 255, 255));
        cmbDestino.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cmbDestino.setForeground(new java.awt.Color(60, 59, 46));

        spinDate.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        spinDate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spinDateStateChanged(evt);
            }
        });

        cmbVuelos.setBackground(new java.awt.Color(255, 255, 255));
        cmbVuelos.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        cmbVuelos.setForeground(new java.awt.Color(60, 59, 46));

        spnNumBoletos.setFont(new java.awt.Font("Maiandra GD", 0, 18)); // NOI18N
        spnNumBoletos.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spnNumBoletosStateChanged(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(60, 59, 46));
        jLabel6.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(27, 55, 58));
        jLabel6.setText("Número de boletos:");

        btnSalir1.setBackground(new java.awt.Color(255, 51, 51));
        btnSalir1.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnSalir1.setForeground(new java.awt.Color(255, 255, 255));
        btnSalir1.setText("Salir");
        btnSalir1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalir1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnSalir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalir1ActionPerformed(evt);
            }
        });

        btnBuscar.setBackground(new java.awt.Color(35, 103, 138));
        btnBuscar.setFont(new java.awt.Font("Maiandra GD", 1, 24)); // NOI18N
        btnBuscar.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscar.setText("Buscar");
        btnBuscar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnBuscar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spnNumBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(117, 117, 117)
                                .addComponent(jLabel3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(btnSalir1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblViajesMsg)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                                    .addComponent(cmbDestino, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabel6)
                            .addComponent(cmbVuelos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(66, 66, 66)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(spinDate)
                            .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE))
                        .addGap(26, 26, 26))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbDestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbOrigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblViajesMsg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cmbVuelos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(spnNumBoletos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnComprar, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                    .addComponent(btnSalir1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        btnComprar.getAccessibleContext().setAccessibleDescription("init");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void spinDateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spinDateStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spinDateStateChanged

    private void spnNumBoletosStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spnNumBoletosStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_spnNumBoletosStateChanged

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        if (vuelos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vuelo no seleccionado.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Vuelo vuelo = vuelos.get(cmbVuelos.getSelectedIndex());
        int numBoletos = (int) spnNumBoletos.getValue();
        double precio = vuelo.getValor().doubleValue() * numBoletos;
        
        if (numBoletos < 1) {
            JOptionPane.showMessageDialog(this, "Indique la cantidad de boletos a comprar.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        if (numBoletos > vuelo.getDisponibles()) {
            JOptionPane.showMessageDialog(this, "La cantidad de boletos eccede los Disponibles.", "Aviso", JOptionPane.WARNING_MESSAGE);
            return;
        }

        CompraBoletoRequest compraBoletoRequest = new CompraBoletoRequest(vuelo.getIdVuelo(), usuario.getIdUsuario(), numBoletos);                
        
        Object[] opciones = {"Confirmar compra", "Cancelar"};

        int opcion = JOptionPane.showOptionDialog(
            this,
            "¿Está seguro que desea comprar el boleto?\n"
                + "Vuelo: " + vuelo.getCodigoVuelo() + "\n"
                + "Viaje: De " + vuelo.getCiudadOrigen().getNombreCiudad() + " a " + vuelo.getCiudadDestino().getNombreCiudad() + "\n"
                + "Fecha: " + vuelo.getHoraSalida() + "\n"
                + "Número de Boletos: " + numBoletos + "\n"
                + "Precio Total: " + precio + "$\n",
            "Confirmación",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opciones,
            opciones[0]
        );

        if (opcion == JOptionPane.YES_OPTION) {
            // Acción de compra
            System.out.println("Compra confirmada.");
            boolean wasBuy = new BoletosController().comprarBoletos(compraBoletoRequest);
            
            if (wasBuy) {
                JOptionPane.showMessageDialog(this, "Compra realizada con éxito.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Hubo problemas al comprar el boleto intente mas tarde.", "Error", JOptionPane.ERROR_MESSAGE);
            }
            
            
            
            
        }
    }//GEN-LAST:event_btnComprarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String origen = ciudades.get(cmbOrigen.getSelectedIndex()).getCodigoCiudad();
        String destino = ciudades.get(cmbDestino.getSelectedIndex()).getCodigoCiudad();
        
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String horaSalida = sdf.format((Date) spinDate.getValue());
        
        vuelos = new VuelosController().obtenerVuelosPorCiudad(origen, destino, horaSalida);
        cmbVuelos.removeAllItems();

        if (vuelos.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vuelo no Disponible.", "Información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            for (Vuelo v : vuelos) {
                cmbVuelos.addItem(v.getCodigoVuelo() + " - Precio: " + v.getValor() + "$ - Disponibles: " + v.getDisponibles());
            }
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnSalir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalir1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalir1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComprarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComprarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComprarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComprarFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ComprarFrm(new Usuario(1)).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnComprar;
    private javax.swing.JButton btnSalir1;
    private javax.swing.JComboBox<String> cmbDestino;
    private javax.swing.JComboBox<String> cmbOrigen;
    private javax.swing.JComboBox<String> cmbVuelos;
    private javax.swing.JDialog dialogConfirm;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblViajesMsg;
    private javax.swing.JSpinner spinDate;
    private javax.swing.JSpinner spnNumBoletos;
    // End of variables declaration//GEN-END:variables
}
