//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ciudades", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Ciudades : object
    {
        
        private int IdCiudadField;
        
        private string CodigoCiudadField;
        
        private string NombreCiudadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCiudad
        {
            get
            {
                return this.IdCiudadField;
            }
            set
            {
                this.IdCiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CodigoCiudad
        {
            get
            {
                return this.CodigoCiudadField;
            }
            set
            {
                this.CodigoCiudadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NombreCiudad
        {
            get
            {
                return this.NombreCiudadField;
            }
            set
            {
                this.NombreCiudadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Vuelos", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Vuelos : object
    {
        
        private int IdVueloField;
        
        private string CodigoVueloField;
        
        private decimal ValorField;
        
        private System.DateTime HoraSalidaField;
        
        private int CapacidadField;
        
        private int DisponiblesField;
        
        private int IdCiudadOrigenField;
        
        private int IdCiudadDestinoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVuelo
        {
            get
            {
                return this.IdVueloField;
            }
            set
            {
                this.IdVueloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CodigoVuelo
        {
            get
            {
                return this.CodigoVueloField;
            }
            set
            {
                this.CodigoVueloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime HoraSalida
        {
            get
            {
                return this.HoraSalidaField;
            }
            set
            {
                this.HoraSalidaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int Capacidad
        {
            get
            {
                return this.CapacidadField;
            }
            set
            {
                this.CapacidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int Disponibles
        {
            get
            {
                return this.DisponiblesField;
            }
            set
            {
                this.DisponiblesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int IdCiudadOrigen
        {
            get
            {
                return this.IdCiudadOrigenField;
            }
            set
            {
                this.IdCiudadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int IdCiudadDestino
        {
            get
            {
                return this.IdCiudadDestinoField;
            }
            set
            {
                this.IdCiudadDestinoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Boletos", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Boletos : object
    {
        
        private int IdBoletoField;
        
        private string NumeroBoletoField;
        
        private System.Nullable<System.DateTime> FechaCompraField;
        
        private decimal PrecioCompraField;
        
        private int IdUsuarioField;
        
        private int IdVueloField;
        
        private System.Nullable<int> IdFacturaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdBoleto
        {
            get
            {
                return this.IdBoletoField;
            }
            set
            {
                this.IdBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroBoleto
        {
            get
            {
                return this.NumeroBoletoField;
            }
            set
            {
                this.NumeroBoletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.Nullable<System.DateTime> FechaCompra
        {
            get
            {
                return this.FechaCompraField;
            }
            set
            {
                this.FechaCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal PrecioCompra
        {
            get
            {
                return this.PrecioCompraField;
            }
            set
            {
                this.PrecioCompraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int IdVuelo
        {
            get
            {
                return this.IdVueloField;
            }
            set
            {
                this.IdVueloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompraBoletoRequest", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class CompraBoletoRequest : object
    {
        
        private int IdUsuarioField;
        
        private ServiceReference1.VueloCompra[] VuelosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReference1.VueloCompra[] Vuelos
        {
            get
            {
                return this.VuelosField;
            }
            set
            {
                this.VuelosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VueloCompra", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class VueloCompra : object
    {
        
        private int IdVueloField;
        
        private int CantidadField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdVuelo
        {
            get
            {
                return this.IdVueloField;
            }
            set
            {
                this.IdVueloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuarios", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Usuarios : object
    {
        
        private int IdUsuarioField;
        
        private string NombreField;
        
        private string UsernameField;
        
        private string PasswordField;
        
        private string TelefonoField;
        
        private string CedulaField;
        
        private string CorreoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Cedula
        {
            get
            {
                return this.CedulaField;
            }
            set
            {
                this.CedulaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facturas", Namespace="http://schemas.datacontract.org/2004/07/ec.edu.monster.modelo")]
    public partial class Facturas : object
    {
        
        private int IdFacturaField;
        
        private string NumeroFacturaField;
        
        private int IdUsuarioField;
        
        private decimal PrecioSinIVAField;
        
        private decimal PrecioConIVAField;
        
        private System.DateTime FechaFacturaField;
        
        private ServiceReference1.Boletos[] BoletosRelacionadosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFactura
        {
            get
            {
                return this.IdFacturaField;
            }
            set
            {
                this.IdFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int IdUsuario
        {
            get
            {
                return this.IdUsuarioField;
            }
            set
            {
                this.IdUsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public decimal PrecioSinIVA
        {
            get
            {
                return this.PrecioSinIVAField;
            }
            set
            {
                this.PrecioSinIVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public decimal PrecioConIVA
        {
            get
            {
                return this.PrecioConIVAField;
            }
            set
            {
                this.PrecioConIVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime FechaFactura
        {
            get
            {
                return this.FechaFacturaField;
            }
            set
            {
                this.FechaFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public ServiceReference1.Boletos[] BoletosRelacionados
        {
            get
            {
                return this.BoletosRelacionadosField;
            }
            set
            {
                this.BoletosRelacionadosField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAeroCondorController")]
    public interface IAeroCondorController
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetCiudades", ReplyAction="http://tempuri.org/IAeroCondorController/GetCiudadesResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Ciudades[]> GetCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerCiudadPorId", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerCiudadPorIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Ciudades> ObtenerCiudadPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/CrearCiudad", ReplyAction="http://tempuri.org/IAeroCondorController/CrearCiudadResponse")]
        System.Threading.Tasks.Task<bool> CrearCiudadAsync(ServiceReference1.Ciudades ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EditarCiudad", ReplyAction="http://tempuri.org/IAeroCondorController/EditarCiudadResponse")]
        System.Threading.Tasks.Task<bool> EditarCiudadAsync(ServiceReference1.Ciudades ciudad);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EliminarCiudad", ReplyAction="http://tempuri.org/IAeroCondorController/EliminarCiudadResponse")]
        System.Threading.Tasks.Task<bool> EliminarCiudadAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ContarCiudades", ReplyAction="http://tempuri.org/IAeroCondorController/ContarCiudadesResponse")]
        System.Threading.Tasks.Task<int> ContarCiudadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ListarCiudadesPorRango", ReplyAction="http://tempuri.org/IAeroCondorController/ListarCiudadesPorRangoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Ciudades[]> ListarCiudadesPorRangoAsync(int desde, int hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetVuelos", ReplyAction="http://tempuri.org/IAeroCondorController/GetVuelosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> GetVuelosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerVueloPorId", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerVueloPorIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Vuelos> ObtenerVueloPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/CrearVuelo", ReplyAction="http://tempuri.org/IAeroCondorController/CrearVueloResponse")]
        System.Threading.Tasks.Task<bool> CrearVueloAsync(ServiceReference1.Vuelos vuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EditarVuelo", ReplyAction="http://tempuri.org/IAeroCondorController/EditarVueloResponse")]
        System.Threading.Tasks.Task<bool> EditarVueloAsync(ServiceReference1.Vuelos vuelo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EliminarVuelo", ReplyAction="http://tempuri.org/IAeroCondorController/EliminarVueloResponse")]
        System.Threading.Tasks.Task<bool> EliminarVueloAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ContarVuelos", ReplyAction="http://tempuri.org/IAeroCondorController/ContarVuelosResponse")]
        System.Threading.Tasks.Task<int> ContarVuelosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ListarVuelosPorRango", ReplyAction="http://tempuri.org/IAeroCondorController/ListarVuelosPorRangoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> ListarVuelosPorRangoAsync(int desde, int hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/BuscarVuelos", ReplyAction="http://tempuri.org/IAeroCondorController/BuscarVuelosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> BuscarVuelosAsync(string origen, string destino, System.DateTime fechaSalida);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetBoletos", ReplyAction="http://tempuri.org/IAeroCondorController/GetBoletosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Boletos[]> GetBoletosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerBoletoPorId", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerBoletoPorIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Boletos> ObtenerBoletoPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/CrearBoleto", ReplyAction="http://tempuri.org/IAeroCondorController/CrearBoletoResponse")]
        System.Threading.Tasks.Task<bool> CrearBoletoAsync(ServiceReference1.Boletos boleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EditarBoleto", ReplyAction="http://tempuri.org/IAeroCondorController/EditarBoletoResponse")]
        System.Threading.Tasks.Task<bool> EditarBoletoAsync(ServiceReference1.Boletos boleto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EliminarBoleto", ReplyAction="http://tempuri.org/IAeroCondorController/EliminarBoletoResponse")]
        System.Threading.Tasks.Task<bool> EliminarBoletoAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ContarBoletos", ReplyAction="http://tempuri.org/IAeroCondorController/ContarBoletosResponse")]
        System.Threading.Tasks.Task<int> ContarBoletosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ListarBoletosPorRango", ReplyAction="http://tempuri.org/IAeroCondorController/ListarBoletosPorRangoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ListarBoletosPorRangoAsync(int desde, int hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/Comprar", ReplyAction="http://tempuri.org/IAeroCondorController/ComprarResponse")]
        System.Threading.Tasks.Task<bool> ComprarAsync(ServiceReference1.CompraBoletoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerBoletosPorUsuario", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerBoletosPorUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ObtenerBoletosPorUsuarioAsync(int idUsuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetUsuarios", ReplyAction="http://tempuri.org/IAeroCondorController/GetUsuariosResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Usuarios[]> GetUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerUsuarioPorId", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerUsuarioPorIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Usuarios> ObtenerUsuarioPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/CrearUsuario", ReplyAction="http://tempuri.org/IAeroCondorController/CrearUsuarioResponse")]
        System.Threading.Tasks.Task<bool> CrearUsuarioAsync(ServiceReference1.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EditarUsuario", ReplyAction="http://tempuri.org/IAeroCondorController/EditarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EditarUsuarioAsync(ServiceReference1.Usuarios usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EliminarUsuario", ReplyAction="http://tempuri.org/IAeroCondorController/EliminarUsuarioResponse")]
        System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ContarUsuarios", ReplyAction="http://tempuri.org/IAeroCondorController/ContarUsuariosResponse")]
        System.Threading.Tasks.Task<int> ContarUsuariosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ListarUsuariosPorRango", ReplyAction="http://tempuri.org/IAeroCondorController/ListarUsuariosPorRangoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Usuarios[]> ListarUsuariosPorRangoAsync(int desde, int hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/Login", ReplyAction="http://tempuri.org/IAeroCondorController/LoginResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Usuarios> LoginAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetFacturas", ReplyAction="http://tempuri.org/IAeroCondorController/GetFacturasResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Facturas[]> GetFacturasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerFacturaPorId", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerFacturaPorIdResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Facturas> ObtenerFacturaPorIdAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/CrearFactura", ReplyAction="http://tempuri.org/IAeroCondorController/CrearFacturaResponse")]
        System.Threading.Tasks.Task<bool> CrearFacturaAsync(ServiceReference1.Facturas factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EditarFactura", ReplyAction="http://tempuri.org/IAeroCondorController/EditarFacturaResponse")]
        System.Threading.Tasks.Task<bool> EditarFacturaAsync(ServiceReference1.Facturas factura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/EliminarFactura", ReplyAction="http://tempuri.org/IAeroCondorController/EliminarFacturaResponse")]
        System.Threading.Tasks.Task<bool> EliminarFacturaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ContarFacturas", ReplyAction="http://tempuri.org/IAeroCondorController/ContarFacturasResponse")]
        System.Threading.Tasks.Task<int> ContarFacturasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ListarFacturasPorRango", ReplyAction="http://tempuri.org/IAeroCondorController/ListarFacturasPorRangoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Facturas[]> ListarFacturasPorRangoAsync(int desde, int hasta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/ObtenerBoletosDeFactura", ReplyAction="http://tempuri.org/IAeroCondorController/ObtenerBoletosDeFacturaResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ObtenerBoletosDeFacturaAsync(int idFactura);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/AsociarBoletosAFactura", ReplyAction="http://tempuri.org/IAeroCondorController/AsociarBoletosAFacturaResponse")]
        System.Threading.Tasks.Task<bool> AsociarBoletosAFacturaAsync(int idFactura, int[] idsBoletos);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAeroCondorController/GetFacturasPorUsuario", ReplyAction="http://tempuri.org/IAeroCondorController/GetFacturasPorUsuarioResponse")]
        System.Threading.Tasks.Task<ServiceReference1.Facturas[]> GetFacturasPorUsuarioAsync(int idUsuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IAeroCondorControllerChannel : ServiceReference1.IAeroCondorController, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class AeroCondorControllerClient : System.ServiceModel.ClientBase<ServiceReference1.IAeroCondorController>, ServiceReference1.IAeroCondorController
    {
        
        /// <summary>
        /// Implemente este método parcial para configurar el punto de conexión de servicio.
        /// </summary>
        /// <param name="serviceEndpoint">El punto de conexión para configurar</param>
        /// <param name="clientCredentials">Credenciales de cliente</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AeroCondorControllerClient() : 
                base(AeroCondorControllerClient.GetDefaultBinding(), AeroCondorControllerClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAeroCondorController.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AeroCondorControllerClient(EndpointConfiguration endpointConfiguration) : 
                base(AeroCondorControllerClient.GetBindingForEndpoint(endpointConfiguration), AeroCondorControllerClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AeroCondorControllerClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AeroCondorControllerClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AeroCondorControllerClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AeroCondorControllerClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AeroCondorControllerClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Ciudades[]> GetCiudadesAsync()
        {
            return base.Channel.GetCiudadesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Ciudades> ObtenerCiudadPorIdAsync(int id)
        {
            return base.Channel.ObtenerCiudadPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CrearCiudadAsync(ServiceReference1.Ciudades ciudad)
        {
            return base.Channel.CrearCiudadAsync(ciudad);
        }
        
        public System.Threading.Tasks.Task<bool> EditarCiudadAsync(ServiceReference1.Ciudades ciudad)
        {
            return base.Channel.EditarCiudadAsync(ciudad);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarCiudadAsync(int id)
        {
            return base.Channel.EliminarCiudadAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ContarCiudadesAsync()
        {
            return base.Channel.ContarCiudadesAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Ciudades[]> ListarCiudadesPorRangoAsync(int desde, int hasta)
        {
            return base.Channel.ListarCiudadesPorRangoAsync(desde, hasta);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> GetVuelosAsync()
        {
            return base.Channel.GetVuelosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Vuelos> ObtenerVueloPorIdAsync(int id)
        {
            return base.Channel.ObtenerVueloPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CrearVueloAsync(ServiceReference1.Vuelos vuelo)
        {
            return base.Channel.CrearVueloAsync(vuelo);
        }
        
        public System.Threading.Tasks.Task<bool> EditarVueloAsync(ServiceReference1.Vuelos vuelo)
        {
            return base.Channel.EditarVueloAsync(vuelo);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarVueloAsync(int id)
        {
            return base.Channel.EliminarVueloAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ContarVuelosAsync()
        {
            return base.Channel.ContarVuelosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> ListarVuelosPorRangoAsync(int desde, int hasta)
        {
            return base.Channel.ListarVuelosPorRangoAsync(desde, hasta);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Vuelos[]> BuscarVuelosAsync(string origen, string destino, System.DateTime fechaSalida)
        {
            return base.Channel.BuscarVuelosAsync(origen, destino, fechaSalida);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Boletos[]> GetBoletosAsync()
        {
            return base.Channel.GetBoletosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Boletos> ObtenerBoletoPorIdAsync(int id)
        {
            return base.Channel.ObtenerBoletoPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CrearBoletoAsync(ServiceReference1.Boletos boleto)
        {
            return base.Channel.CrearBoletoAsync(boleto);
        }
        
        public System.Threading.Tasks.Task<bool> EditarBoletoAsync(ServiceReference1.Boletos boleto)
        {
            return base.Channel.EditarBoletoAsync(boleto);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarBoletoAsync(int id)
        {
            return base.Channel.EliminarBoletoAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ContarBoletosAsync()
        {
            return base.Channel.ContarBoletosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ListarBoletosPorRangoAsync(int desde, int hasta)
        {
            return base.Channel.ListarBoletosPorRangoAsync(desde, hasta);
        }
        
        public System.Threading.Tasks.Task<bool> ComprarAsync(ServiceReference1.CompraBoletoRequest request)
        {
            return base.Channel.ComprarAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ObtenerBoletosPorUsuarioAsync(int idUsuario)
        {
            return base.Channel.ObtenerBoletosPorUsuarioAsync(idUsuario);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Usuarios[]> GetUsuariosAsync()
        {
            return base.Channel.GetUsuariosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Usuarios> ObtenerUsuarioPorIdAsync(int id)
        {
            return base.Channel.ObtenerUsuarioPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CrearUsuarioAsync(ServiceReference1.Usuarios usuario)
        {
            return base.Channel.CrearUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EditarUsuarioAsync(ServiceReference1.Usuarios usuario)
        {
            return base.Channel.EditarUsuarioAsync(usuario);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarUsuarioAsync(int id)
        {
            return base.Channel.EliminarUsuarioAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ContarUsuariosAsync()
        {
            return base.Channel.ContarUsuariosAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Usuarios[]> ListarUsuariosPorRangoAsync(int desde, int hasta)
        {
            return base.Channel.ListarUsuariosPorRangoAsync(desde, hasta);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Usuarios> LoginAsync(string username, string password)
        {
            return base.Channel.LoginAsync(username, password);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Facturas[]> GetFacturasAsync()
        {
            return base.Channel.GetFacturasAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Facturas> ObtenerFacturaPorIdAsync(int id)
        {
            return base.Channel.ObtenerFacturaPorIdAsync(id);
        }
        
        public System.Threading.Tasks.Task<bool> CrearFacturaAsync(ServiceReference1.Facturas factura)
        {
            return base.Channel.CrearFacturaAsync(factura);
        }
        
        public System.Threading.Tasks.Task<bool> EditarFacturaAsync(ServiceReference1.Facturas factura)
        {
            return base.Channel.EditarFacturaAsync(factura);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarFacturaAsync(int id)
        {
            return base.Channel.EliminarFacturaAsync(id);
        }
        
        public System.Threading.Tasks.Task<int> ContarFacturasAsync()
        {
            return base.Channel.ContarFacturasAsync();
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Facturas[]> ListarFacturasPorRangoAsync(int desde, int hasta)
        {
            return base.Channel.ListarFacturasPorRangoAsync(desde, hasta);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Boletos[]> ObtenerBoletosDeFacturaAsync(int idFactura)
        {
            return base.Channel.ObtenerBoletosDeFacturaAsync(idFactura);
        }
        
        public System.Threading.Tasks.Task<bool> AsociarBoletosAFacturaAsync(int idFactura, int[] idsBoletos)
        {
            return base.Channel.AsociarBoletosAFacturaAsync(idFactura, idsBoletos);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.Facturas[]> GetFacturasPorUsuarioAsync(int idUsuario)
        {
            return base.Channel.GetFacturasPorUsuarioAsync(idUsuario);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAeroCondorController))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAeroCondorController))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55325/ec.edu.monster.controlador/AeroCondorController.svc");
            }
            throw new System.InvalidOperationException(string.Format("No se pudo encontrar un punto de conexión con el nombre \"{0}\".", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AeroCondorControllerClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAeroCondorController);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AeroCondorControllerClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAeroCondorController);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAeroCondorController,
        }
    }
}
